[gme.py, line 159, in unZip()] [ERROR] MGP_PrezziConvenzionali2018040120180430.zip not found. Retrying...
[gme.py, line 159, in unZip()] [ERROR] MGP_PrezziConvenzionali2018040120180430.zip not found. Retrying...
[gme.py, line 159, in unZip()] [ERROR] MGP_PrezziConvenzionali2018040120180430.zip not found. Retrying...
[gme.py, line 159, in unZip()] [ERROR] MGP_PrezziConvenzionali2018040120180430.zip not found. Retrying...
[gme.py, line 159, in unZip()] [ERROR] MGP_PrezziConvenzionali2018040120180430.zip not found. Retrying...
[gme.py, line 159, in unZip()] [ERROR] MGP_PrezziConvenzionali2018040120180430.zip not found. Retrying...
[gme.py, line 159, in unZip()] [ERROR] MGP_PrezziConvenzionali2018040120180430.zip not found. Retrying...
[gme.py, line 159, in unZip()] [ERROR] MGP_PrezziConvenzionali2018040120180430.zip not found. Retrying...
[gme.py, line 159, in unZip()] [ERROR] MGP_PrezziConvenzionali2018040120180430.zip not found. Retrying...
[gme.py, line 159, in unZip()] [ERROR] MGP_PrezziConvenzionali2018040120180430.zip not found. Retrying...
[gme.py, line 159, in unZip()] [ERROR] MGP_PrezziConvenzionali2018040120180430.zip not found. Retrying...
[gme.py, line 159, in unZip()] [ERROR] MGP_PrezziConvenzionali2018040120180430.zip not found. Retrying...
[gme.py, line 159, in unZip()] [ERROR] MGP_PrezziConvenzionali2018040120180430.zip not found. Retrying...
[gme.py, line 159, in unZip()] [ERROR] MGP_PrezziConvenzionali2018040120180430.zip not found. Retrying...
[gme.py, line 159, in unZip()] [ERROR] MGP_PrezziConvenzionali2018040120180430.zip not found. Retrying...
[gme.py, line 159, in unZip()] [ERROR] MGP_PrezziConvenzionali2018040120180430.zip not found. Retrying...
[gme.py, line 159, in unZip()] [ERROR] MGP_PrezziConvenzionali2018040120180430.zip not found. Retrying...
[gme.py, line 159, in unZip()] [ERROR] MGP_PrezziConvenzionali2018040120180430.zip not found. Retrying...
[gme.py, line 106, in getData()] [WARNING] Trying again...
[gme.py, line 106, in getData()] [WARNING] Trying again...
[gme.py, line 107, in getData()] [WARNING] Trying again...
[gme.py, line 107, in getData()] [WARNING] Trying again...
[gme.py, line 107, in getData()] [WARNING] Trying again...
[gme.py, line 107, in getData()] [WARNING] Trying again...
[gme.py, line 106, in getData()] [WARNING] Trying again...
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 68, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 117, in getData()] [WARNING] Trying again...
[gme.py, line 69, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 69, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 69, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 69, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 69, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 69, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 69, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 69, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 69, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 119, in getData()] [WARNING] Trying again...
[gme.py, line 119, in getData()] [WARNING] Trying again...
[gme.py, line 119, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 120, in getData()] [WARNING] Trying again...
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] Connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] GME connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] GME connection failed. Trying again.
[gme.py, line 71, in passRestrictions()] [ERROR] GME connection failed. Trying again.
[gme.py, line 125, in getData()] [WARNING] Trying again...
[gme.py, line 125, in getData()] [WARNING] Trying again...
[gme.py, line 125, in getData()] [WARNING] Trying again...
[gme.py, line 125, in getData()] [WARNING] Trying again...
[gme.py, line 183, in checkDownload()] [ERROR] MGP_LimitiTransito2017020120170228.zip download failed
[gme.py, line 130, in getData()] [WARNING] Trying again...
[gme.py, line 130, in getData()] [WARNING] Trying again...
[gme.py, line 130, in getData()] [WARNING] Trying again...
[gme.py, line 130, in getData()] [WARNING] Trying again...
[gme.py, line 130, in getData()] [WARNING] Trying again...
[gme.py, line 130, in getData()] [WARNING] Trying again...
[gme.py, line 126, in getData()] [WARNING] Trying again...
[gme.py, line 126, in getData()] [WARNING] Trying again...
[gme.py, line 126, in getData()] [WARNING] Trying again...
[gme.py, line 126, in getData()] [WARNING] Trying again...
[gme.py, line 126, in getData()] [WARNING] Trying again...
[gme.py, line 126, in getData()] [WARNING] Trying again...
[gme.py, line 126, in getData()] [WARNING] Trying again...
[gme.py, line 126, in getData()] [WARNING] Trying again...
